// prettier-ignore
/* eslint-disable */
// @ts-nocheck
/* auto-generated by NAPI-RS */

const { readFileSync } = require('node:fs')
let nativeBinding = null;
const loadErrors = [];

const isMusl = () => {
  let musl = false;
  if (process.platform === 'linux') {
    musl = isMuslFromFilesystem();
    if (musl === null) {
      musl = isMuslFromReport();
    }
    if (musl === null) {
      musl = isMuslFromChildProcess();
    }
  }
  return musl;
};

const isFileMusl = f => f.includes('libc.musl-') || f.includes('ld-musl-');

const isMuslFromFilesystem = () => {
  try {
    return readFileSync('/usr/bin/ldd', 'utf-8').includes('musl');
  } catch {
    return null;
  }
};

const isMuslFromReport = () => {
  let report = null;
  if (typeof process.report?.getReport === 'function') {
    process.report.excludeNetwork = true;
    report = process.report.getReport();
  }
  if (!report) {
    return null;
  }
  if (report.header && report.header.glibcVersionRuntime) {
    return false;
  }
  if (Array.isArray(report.sharedObjects)) {
    if (report.sharedObjects.some(isFileMusl)) {
      return true;
    }
  }
  return false;
};

const isMuslFromChildProcess = () => {
  try {
    return require('child_process')
      .execSync('ldd --version', { encoding: 'utf8' })
      .includes('musl');
  } catch (e) {
    // If we reach this case, we don't know if the system is musl or not, so is better to just fallback to false
    return false;
  }
};

function requireNative() {
  if (process.env.NAPI_RS_NATIVE_LIBRARY_PATH) {
    try {
      return require(process.env.NAPI_RS_NATIVE_LIBRARY_PATH);
    } catch (err) {
      loadErrors.push(err);
    }
  } else if (process.platform === 'android') {
    if (process.arch === 'arm64') {
      try {
        return require('./server-native.android-arm64.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@affine/server-native-android-arm64');
        const bindingPackageVersion =
          require('@affine/server-native-android-arm64/package.json').version;
        if (
          bindingPackageVersion !== '0.26.3' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.26.3 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./server-native.android-arm-eabi.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@affine/server-native-android-arm-eabi');
        const bindingPackageVersion =
          require('@affine/server-native-android-arm-eabi/package.json').version;
        if (
          bindingPackageVersion !== '0.26.3' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.26.3 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else {
      loadErrors.push(
        new Error(`Unsupported architecture on Android ${process.arch}`)
      );
    }
  } else if (process.platform === 'win32') {
    if (process.arch === 'x64') {
      if (
        process.config?.variables?.shlib_suffix === 'dll.a' ||
        process.config?.variables?.node_target_type === 'shared_library'
      ) {
        try {
          return require('./server-native.win32-x64-gnu.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@affine/server-native-win32-x64-gnu');
          const bindingPackageVersion =
            require('@affine/server-native-win32-x64-gnu/package.json').version;
          if (
            bindingPackageVersion !== '0.26.3' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.26.3 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      } else {
        try {
          return require('./server-native.win32-x64-msvc.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@affine/server-native-win32-x64-msvc');
          const bindingPackageVersion =
            require('@affine/server-native-win32-x64-msvc/package.json').version;
          if (
            bindingPackageVersion !== '0.26.3' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.26.3 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      }
    } else if (process.arch === 'ia32') {
      try {
        return require('./server-native.win32-ia32-msvc.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@affine/server-native-win32-ia32-msvc');
        const bindingPackageVersion =
          require('@affine/server-native-win32-ia32-msvc/package.json').version;
        if (
          bindingPackageVersion !== '0.26.3' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.26.3 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./server-native.win32-arm64-msvc.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@affine/server-native-win32-arm64-msvc');
        const bindingPackageVersion =
          require('@affine/server-native-win32-arm64-msvc/package.json').version;
        if (
          bindingPackageVersion !== '0.26.3' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.26.3 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else {
      loadErrors.push(
        new Error(`Unsupported architecture on Windows: ${process.arch}`)
      );
    }
  } else if (process.platform === 'darwin') {
    try {
      return require('./server-native.darwin-universal.node');
    } catch (e) {
      loadErrors.push(e);
    }
    try {
      const binding = require('@affine/server-native-darwin-universal');
      const bindingPackageVersion =
        require('@affine/server-native-darwin-universal/package.json').version;
      if (
        bindingPackageVersion !== '0.26.3' &&
        process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
        process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
      ) {
        throw new Error(
          `Native binding package version mismatch, expected 0.26.3 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`
        );
      }
      return binding;
    } catch (e) {
      loadErrors.push(e);
    }
    if (process.arch === 'x64') {
      try {
        return require('./server-native.darwin-x64.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@affine/server-native-darwin-x64');
        const bindingPackageVersion =
          require('@affine/server-native-darwin-x64/package.json').version;
        if (
          bindingPackageVersion !== '0.26.3' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.26.3 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./server-native.darwin-arm64.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@affine/server-native-darwin-arm64');
        const bindingPackageVersion =
          require('@affine/server-native-darwin-arm64/package.json').version;
        if (
          bindingPackageVersion !== '0.26.3' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.26.3 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else {
      loadErrors.push(
        new Error(`Unsupported architecture on macOS: ${process.arch}`)
      );
    }
  } else if (process.platform === 'freebsd') {
    if (process.arch === 'x64') {
      try {
        return require('./server-native.freebsd-x64.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@affine/server-native-freebsd-x64');
        const bindingPackageVersion =
          require('@affine/server-native-freebsd-x64/package.json').version;
        if (
          bindingPackageVersion !== '0.26.3' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.26.3 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./server-native.freebsd-arm64.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@affine/server-native-freebsd-arm64');
        const bindingPackageVersion =
          require('@affine/server-native-freebsd-arm64/package.json').version;
        if (
          bindingPackageVersion !== '0.26.3' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.26.3 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else {
      loadErrors.push(
        new Error(`Unsupported architecture on FreeBSD: ${process.arch}`)
      );
    }
  } else if (process.platform === 'linux') {
    if (process.arch === 'x64') {
      if (isMusl()) {
        try {
          return require('./server-native.linux-x64-musl.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@affine/server-native-linux-x64-musl');
          const bindingPackageVersion =
            require('@affine/server-native-linux-x64-musl/package.json').version;
          if (
            bindingPackageVersion !== '0.26.3' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.26.3 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      } else {
        try {
          return require('./server-native.linux-x64-gnu.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@affine/server-native-linux-x64-gnu');
          const bindingPackageVersion =
            require('@affine/server-native-linux-x64-gnu/package.json').version;
          if (
            bindingPackageVersion !== '0.26.3' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.26.3 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      }
    } else if (process.arch === 'arm64') {
      if (isMusl()) {
        try {
          return require('./server-native.linux-arm64-musl.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@affine/server-native-linux-arm64-musl');
          const bindingPackageVersion =
            require('@affine/server-native-linux-arm64-musl/package.json').version;
          if (
            bindingPackageVersion !== '0.26.3' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.26.3 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      } else {
        try {
          return require('./server-native.linux-arm64-gnu.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@affine/server-native-linux-arm64-gnu');
          const bindingPackageVersion =
            require('@affine/server-native-linux-arm64-gnu/package.json').version;
          if (
            bindingPackageVersion !== '0.26.3' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.26.3 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      }
    } else if (process.arch === 'arm') {
      if (isMusl()) {
        try {
          return require('./server-native.linux-arm-musleabihf.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@affine/server-native-linux-arm-musleabihf');
          const bindingPackageVersion =
            require('@affine/server-native-linux-arm-musleabihf/package.json').version;
          if (
            bindingPackageVersion !== '0.26.3' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.26.3 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      } else {
        try {
          return require('./server-native.linux-arm-gnueabihf.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@affine/server-native-linux-arm-gnueabihf');
          const bindingPackageVersion =
            require('@affine/server-native-linux-arm-gnueabihf/package.json').version;
          if (
            bindingPackageVersion !== '0.26.3' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.26.3 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      }
    } else if (process.arch === 'loong64') {
      if (isMusl()) {
        try {
          return require('./server-native.linux-loong64-musl.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@affine/server-native-linux-loong64-musl');
          const bindingPackageVersion =
            require('@affine/server-native-linux-loong64-musl/package.json').version;
          if (
            bindingPackageVersion !== '0.26.3' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.26.3 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      } else {
        try {
          return require('./server-native.linux-loong64-gnu.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@affine/server-native-linux-loong64-gnu');
          const bindingPackageVersion =
            require('@affine/server-native-linux-loong64-gnu/package.json').version;
          if (
            bindingPackageVersion !== '0.26.3' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.26.3 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      }
    } else if (process.arch === 'riscv64') {
      if (isMusl()) {
        try {
          return require('./server-native.linux-riscv64-musl.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@affine/server-native-linux-riscv64-musl');
          const bindingPackageVersion =
            require('@affine/server-native-linux-riscv64-musl/package.json').version;
          if (
            bindingPackageVersion !== '0.26.3' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.26.3 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      } else {
        try {
          return require('./server-native.linux-riscv64-gnu.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@affine/server-native-linux-riscv64-gnu');
          const bindingPackageVersion =
            require('@affine/server-native-linux-riscv64-gnu/package.json').version;
          if (
            bindingPackageVersion !== '0.26.3' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.26.3 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      }
    } else if (process.arch === 'ppc64') {
      try {
        return require('./server-native.linux-ppc64-gnu.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@affine/server-native-linux-ppc64-gnu');
        const bindingPackageVersion =
          require('@affine/server-native-linux-ppc64-gnu/package.json').version;
        if (
          bindingPackageVersion !== '0.26.3' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.26.3 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else if (process.arch === 's390x') {
      try {
        return require('./server-native.linux-s390x-gnu.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@affine/server-native-linux-s390x-gnu');
        const bindingPackageVersion =
          require('@affine/server-native-linux-s390x-gnu/package.json').version;
        if (
          bindingPackageVersion !== '0.26.3' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.26.3 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else {
      loadErrors.push(
        new Error(`Unsupported architecture on Linux: ${process.arch}`)
      );
    }
  } else if (process.platform === 'openharmony') {
    if (process.arch === 'arm64') {
      try {
        return require('./server-native.openharmony-arm64.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@affine/server-native-openharmony-arm64');
        const bindingPackageVersion =
          require('@affine/server-native-openharmony-arm64/package.json').version;
        if (
          bindingPackageVersion !== '0.26.3' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.26.3 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else if (process.arch === 'x64') {
      try {
        return require('./server-native.openharmony-x64.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@affine/server-native-openharmony-x64');
        const bindingPackageVersion =
          require('@affine/server-native-openharmony-x64/package.json').version;
        if (
          bindingPackageVersion !== '0.26.3' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.26.3 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./server-native.openharmony-arm.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@affine/server-native-openharmony-arm');
        const bindingPackageVersion =
          require('@affine/server-native-openharmony-arm/package.json').version;
        if (
          bindingPackageVersion !== '0.26.3' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.26.3 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else {
      loadErrors.push(
        new Error(`Unsupported architecture on OpenHarmony: ${process.arch}`)
      );
    }
  } else {
    loadErrors.push(
      new Error(
        `Unsupported OS: ${process.platform}, architecture: ${process.arch}`
      )
    );
  }
}

nativeBinding = requireNative();

if (!nativeBinding || process.env.NAPI_RS_FORCE_WASI) {
  let wasiBinding = null;
  let wasiBindingError = null;
  try {
    wasiBinding = require('./server-native.wasi.cjs');
    nativeBinding = wasiBinding;
  } catch (err) {
    if (process.env.NAPI_RS_FORCE_WASI) {
      wasiBindingError = err;
    }
  }
  if (!nativeBinding) {
    try {
      wasiBinding = require('@affine/server-native-wasm32-wasi');
      nativeBinding = wasiBinding;
    } catch (err) {
      if (process.env.NAPI_RS_FORCE_WASI) {
        wasiBindingError.cause = err;
        loadErrors.push(err);
      }
    }
  }
  if (process.env.NAPI_RS_FORCE_WASI === 'error' && !wasiBinding) {
    const error = new Error(
      'WASI binding not found and NAPI_RS_FORCE_WASI is set to error'
    );
    error.cause = wasiBindingError;
    throw error;
  }
}

if (!nativeBinding) {
  if (loadErrors.length > 0) {
    throw new Error(
      `Cannot find native binding. ` +
        `npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). ` +
        'Please try `npm i` again after removing both package-lock.json and node_modules directory.',
      {
        cause: loadErrors.reduce((err, cur) => {
          cur.cause = err;
          return cur;
        }),
      }
    );
  }
  throw new Error(`Failed to load native binding`);
}

module.exports = nativeBinding;
module.exports.LlmStreamHandle = nativeBinding.LlmStreamHandle;
module.exports.Tokenizer = nativeBinding.Tokenizer;
module.exports.addDocToRootDoc = nativeBinding.addDocToRootDoc;
module.exports.AFFINE_PRO_LICENSE_AES_KEY =
  nativeBinding.AFFINE_PRO_LICENSE_AES_KEY;
module.exports.AFFINE_PRO_PUBLIC_KEY = nativeBinding.AFFINE_PRO_PUBLIC_KEY;
module.exports.buildFoldersDocIdNapi = nativeBinding.buildFoldersDocIdNapi;
module.exports.collectionAddDocsNative = nativeBinding.collectionAddDocsNative;
module.exports.collectionCreateNative = nativeBinding.collectionCreateNative;
module.exports.collectionDeleteNative = nativeBinding.collectionDeleteNative;
module.exports.collectionListNative = nativeBinding.collectionListNative;
module.exports.collectionRemoveDocsNative =
  nativeBinding.collectionRemoveDocsNative;
module.exports.collectionUpdateNative = nativeBinding.collectionUpdateNative;
module.exports.createDocWithMarkdown = nativeBinding.createDocWithMarkdown;
module.exports.databaseAddRowsNative = nativeBinding.databaseAddRowsNative;
module.exports.databaseCreateNative = nativeBinding.databaseCreateNative;
module.exports.databaseUpdateCellsNative =
  nativeBinding.databaseUpdateCellsNative;
module.exports.docMoveToFolderNative = nativeBinding.docMoveToFolderNative;
module.exports.folderCreateNative = nativeBinding.folderCreateNative;
module.exports.folderDeleteNative = nativeBinding.folderDeleteNative;
module.exports.folderGetHierarchyNative =
  nativeBinding.folderGetHierarchyNative;
module.exports.folderListNative = nativeBinding.folderListNative;
module.exports.folderMoveNative = nativeBinding.folderMoveNative;
module.exports.fromModelName = nativeBinding.fromModelName;
module.exports.getMime = nativeBinding.getMime;
module.exports.htmlSanitize = nativeBinding.htmlSanitize;
module.exports.isFoldersDocumentNapi = nativeBinding.isFoldersDocumentNapi;
module.exports.llmDispatch = nativeBinding.llmDispatch;
module.exports.llmDispatchStream = nativeBinding.llmDispatchStream;
module.exports.llmEmbeddingDispatch = nativeBinding.llmEmbeddingDispatch;
module.exports.llmRerankDispatch = nativeBinding.llmRerankDispatch;
module.exports.llmStructuredDispatch = nativeBinding.llmStructuredDispatch;
module.exports.mergeUpdatesInApplyWay = nativeBinding.mergeUpdatesInApplyWay;
module.exports.mintChallengeResponse = nativeBinding.mintChallengeResponse;
module.exports.parseDoc = nativeBinding.parseDoc;
module.exports.parseDocFromBinary = nativeBinding.parseDocFromBinary;
module.exports.parseDocToMarkdown = nativeBinding.parseDocToMarkdown;
module.exports.parsePageDoc = nativeBinding.parsePageDoc;
module.exports.parseWorkspaceDoc = nativeBinding.parseWorkspaceDoc;
module.exports.processImage = nativeBinding.processImage;
module.exports.readAllDocIdsFromRootDoc =
  nativeBinding.readAllDocIdsFromRootDoc;
module.exports.updateDocProperties = nativeBinding.updateDocProperties;
module.exports.updateDocTitle = nativeBinding.updateDocTitle;
module.exports.updateDocWithMarkdown = nativeBinding.updateDocWithMarkdown;
module.exports.updateRootDocMetaTitle = nativeBinding.updateRootDocMetaTitle;
module.exports.verifyChallengeResponse = nativeBinding.verifyChallengeResponse;
